import { SWRConfig } from "swr";
import "@/styles/globals.css";
import Head from "next/head";
import { Arimo } from "next/font/google";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

const fetcher = (...args) => fetch(...args).then((response) => response.json());

const arimo = Arimo({
  variable: "--font-arimo",
  subsets: ["latin"],
});

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Book My Bite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico.jpg" />
      </Head>
      <div className={`${arimo.variable}`}></div>
      <SWRConfig value={{ fetcher }}>
        <Header />
        <Component {...pageProps} />
        <Footer />
      </SWRConfig>
    </>
  );
}
