import Head from "next/head";
import Link from "next/link";
import { Arimo } from "next/font/google";
import Image from "next/image";

const arimo = Arimo({
  variable: "--font-arimo",
  subsets: ["latin"],
});

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${arimo.variable}`}>
        <main>
          <Image
            src={"/landing.jpg"}
            width="3440"
            height="1440"
            alt="landing page image"
          ></Image>
          <Link href={"/restaurants"}>
            <button>Book My Bite </button>
          </Link>
        </main>
      </div>
    </>
  );
};

export default Home;
