import Head from "next/head";
import useSWR from "swr";
import { Arimo } from "next/font/google";
import RestaurantList from "@/components/restaurantList/RestaurantList";

const arimo = Arimo({
  variable: "--font-arimo",
  subsets: ["latin"],
});

const Home = () => {
  const baseURL = process.env.NEXT_PUBLIC_API_URL;

  const { data, error, isLoading } = useSWR(`${baseURL}api/restaurants`);

  if (error) console.error(error);
  if (!data) return;
  if (isLoading) return <p>Loading...</p>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${arimo.variable}`}>
        <main>
          <h1>Home page</h1>
          <RestaurantList data={data} />
        </main>
      </div>
    </>
  );
};

export default Home;
